import type { Config } from "tailwindcss";

const withAlpha = (name: string) => `rgb(var(${name}) / <alpha-value>)`;

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: withAlpha("--background-rgb"),
        surface: withAlpha("--surface-rgb"),
        "surface-dim": withAlpha("--surface-dim-rgb"),
        "surface-container-lowest": withAlpha("--surface-container-lowest-rgb"),
        "surface-container-low": withAlpha("--surface-container-low-rgb"),
        "surface-container": withAlpha("--surface-container-rgb"),
        "surface-container-high": withAlpha("--surface-container-high-rgb"),
        "surface-container-highest": withAlpha("--surface-container-highest-rgb"),
        "surface-bright": withAlpha("--surface-bright-rgb"),
        "surface-variant": withAlpha("--surface-variant-rgb"),
        primary: withAlpha("--primary-rgb"),
        "primary-dim": withAlpha("--primary-dim-rgb"),
        "primary-container": withAlpha("--primary-container-rgb"),
        "on-primary": withAlpha("--on-primary-rgb"),
        secondary: withAlpha("--secondary-rgb"),
        "secondary-container": withAlpha("--secondary-container-rgb"),
        "on-secondary": withAlpha("--on-secondary-rgb"),
        tertiary: withAlpha("--tertiary-rgb"),
        "tertiary-dim": withAlpha("--tertiary-dim-rgb"),
        "tertiary-container": withAlpha("--tertiary-container-rgb"),
        "on-tertiary": withAlpha("--on-tertiary-rgb"),
        error: withAlpha("--error-rgb"),
        outline: withAlpha("--outline-rgb"),
        "outline-variant": withAlpha("--outline-variant-rgb"),
        "on-surface": withAlpha("--on-surface-rgb"),
        "on-surface-variant": withAlpha("--on-surface-variant-rgb"),
        "on-background": withAlpha("--on-background-rgb"),
      },
      fontFamily: {
        sans: ["var(--font-instrument)", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-instrument)", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["var(--font-plex-mono)", "ui-monospace", "monospace"],
        mono: ["var(--font-plex-mono)", "ui-monospace", "monospace"],
      },
      spacing: {
        18: "4.5rem",
        88: "22rem",
        112: "28rem",
        128: "32rem",
      },
      opacity: {
        4: "0.04",
        6: "0.06",
        7: "0.07",
        8: "0.08",
        12: "0.12",
        14: "0.14",
        16: "0.16",
        18: "0.18",
        22: "0.22",
        24: "0.24",
        28: "0.28",
        26: "0.26",
        32: "0.32",
        33: "0.33",
        34: "0.34",
        35: "0.35",
        36: "0.36",
        38: "0.38",
        42: "0.42",
        45: "0.45",
        48: "0.48",
        50: "0.5",
        52: "0.52",
        55: "0.55",
        62: "0.62",
        65: "0.65",
        68: "0.68",
        70: "0.7",
        72: "0.72",
        75: "0.75",
        78: "0.78",
        80: "0.8",
        85: "0.85",
        88: "0.88",
        92: "0.92",
        94: "0.94",
        95: "0.95",
        96: "0.96",
        98: "0.98",
      },
      borderColor: {
        DEFAULT: withAlpha("--outline-variant-rgb"),
      },
      boxShadow: {
        surface: "0 18px 44px rgba(0, 0, 0, 0.34)",
        "surface-lg": "0 28px 80px rgba(0, 0, 0, 0.48)",
      },
    },
  },
  plugins: [],
};

export default config;
